### PR TITLE
Add max idle conns per host

### PR DESCRIPTION
**Pull request by brenol**
Really love defaults and my idea of using http.RoundTripper interface was a bad one, sorry about that.

This is a small change that can bring up a performance improvement 👍

### CODE REVIEW

**Comment by brenol** [comment]
As the coverage is reduced, I'll make this PR more useful increasing the coverage of types.go.

**Comment by brenol** [comment]
Not sure on how I can get that patch one from failing...

**Comment by TwinProduction** [comment]
I'm not particularly against the change, but is there a specific reason why you think  MaxIdleConns/MaxIdleConnsPerHost should be 150? 
Sending 150 requests per second seems a bit excessive, I believe the default is 2?

**Comment by brenol** [comment]
Yep, the default is 2. I just added 150 as a 'magic number'...

Perhaps 100 is a better number? I think 2 is really low, specially if you have a higher latency (due to distance or something) and really makes the connection reuse be really bad (as stdlib starts closing idle conns, as far as I know but I might be wrong though)

**Comment by TwinProduction** [comment]
I've done some research on this topic, and you are indeed right that increasing these parameters will provide a performance improvement, however, I think that 150 is a bit too high.

Most performance improvements were observed on tools that sends a lot of requests per second.

In this case, sending this many requests will likely cause the user to get rate limited by Pastebin.

That said, this is a tool, and it can be used however desired by its users and it's not my place to decide. 

As such, I think setting these two values to 50 should be a good compromise - it's a lot better than the default MaxIdleConnsPerHost of 2.

What do you think?

**Comment by brenol** [comment]
I agree. I started thinking the same when you said that 150 would be too high and when I made the change I completely forgot about rate limiting. I'll change the PR.

**Comment by TwinProduction** [comment]
I'm fine with this, thanks for contributing! :)

**Review by TwinProduction — APPROVED** [review]

**Comment by TwinProduction** [comment]
Released in [v0.0.3](https://github.com/TwinProduction/go-pastebin/releases/tag/v0.0.3)

**Pull request merged**
